//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Msd_V2.MaptqCN {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsSoap", Namespace="http://tempuri.org//ws")]
    public partial class ws : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback runWSxmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback runWSobjOperationCompleted;
        
        private System.Threading.SendOrPostCallback getScoresXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback getScoresObjOperationCompleted;
        
        private System.Threading.SendOrPostCallback combineScoresXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback combineScoresObjOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ws() {
            this.Url = global::Msd_V2.Properties.Settings.Default.Msd_V2_MaptqCN_ws;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event runWSxmlCompletedEventHandler runWSxmlCompleted;
        
        /// <remarks/>
        public event runWSobjCompletedEventHandler runWSobjCompleted;
        
        /// <remarks/>
        public event getScoresXmlCompletedEventHandler getScoresXmlCompleted;
        
        /// <remarks/>
        public event getScoresObjCompletedEventHandler getScoresObjCompleted;
        
        /// <remarks/>
        public event combineScoresXmlCompletedEventHandler combineScoresXmlCompleted;
        
        /// <remarks/>
        public event combineScoresObjCompletedEventHandler combineScoresObjCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org//ws/runWSxml", RequestNamespace="http://tempuri.org//ws", ResponseNamespace="http://tempuri.org//ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode runWSxml(
                    string requesttype, 
                    string securecode, 
                    string clientid, 
                    string jobid, 
                    string languageid, 
                    string projectid, 
                    string candidateid, 
                    string instrumentid, 
                    string reportid, 
                    string normsetid, 
                    string firstname, 
                    string lastname, 
                    string genderid, 
                    string ipaddress, 
                    string returnurl, 
                    string notifylist, 
                    string emailaddress, 
                    string resultposturl, 
                    string resultpostheaders, 
                    string resultpostbodytemplate) {
            object[] results = this.Invoke("runWSxml", new object[] {
                        requesttype,
                        securecode,
                        clientid,
                        jobid,
                        languageid,
                        projectid,
                        candidateid,
                        instrumentid,
                        reportid,
                        normsetid,
                        firstname,
                        lastname,
                        genderid,
                        ipaddress,
                        returnurl,
                        notifylist,
                        emailaddress,
                        resultposturl,
                        resultpostheaders,
                        resultpostbodytemplate});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void runWSxmlAsync(
                    string requesttype, 
                    string securecode, 
                    string clientid, 
                    string jobid, 
                    string languageid, 
                    string projectid, 
                    string candidateid, 
                    string instrumentid, 
                    string reportid, 
                    string normsetid, 
                    string firstname, 
                    string lastname, 
                    string genderid, 
                    string ipaddress, 
                    string returnurl, 
                    string notifylist, 
                    string emailaddress, 
                    string resultposturl, 
                    string resultpostheaders, 
                    string resultpostbodytemplate) {
            this.runWSxmlAsync(requesttype, securecode, clientid, jobid, languageid, projectid, candidateid, instrumentid, reportid, normsetid, firstname, lastname, genderid, ipaddress, returnurl, notifylist, emailaddress, resultposturl, resultpostheaders, resultpostbodytemplate, null);
        }
        
        /// <remarks/>
        public void runWSxmlAsync(
                    string requesttype, 
                    string securecode, 
                    string clientid, 
                    string jobid, 
                    string languageid, 
                    string projectid, 
                    string candidateid, 
                    string instrumentid, 
                    string reportid, 
                    string normsetid, 
                    string firstname, 
                    string lastname, 
                    string genderid, 
                    string ipaddress, 
                    string returnurl, 
                    string notifylist, 
                    string emailaddress, 
                    string resultposturl, 
                    string resultpostheaders, 
                    string resultpostbodytemplate, 
                    object userState) {
            if ((this.runWSxmlOperationCompleted == null)) {
                this.runWSxmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrunWSxmlOperationCompleted);
            }
            this.InvokeAsync("runWSxml", new object[] {
                        requesttype,
                        securecode,
                        clientid,
                        jobid,
                        languageid,
                        projectid,
                        candidateid,
                        instrumentid,
                        reportid,
                        normsetid,
                        firstname,
                        lastname,
                        genderid,
                        ipaddress,
                        returnurl,
                        notifylist,
                        emailaddress,
                        resultposturl,
                        resultpostheaders,
                        resultpostbodytemplate}, this.runWSxmlOperationCompleted, userState);
        }
        
        private void OnrunWSxmlOperationCompleted(object arg) {
            if ((this.runWSxmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.runWSxmlCompleted(this, new runWSxmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org//ws/runWSobj", RequestNamespace="http://tempuri.org//ws", ResponseNamespace="http://tempuri.org//ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public wsResponseObj runWSobj(wsRequestObj reqobj) {
            object[] results = this.Invoke("runWSobj", new object[] {
                        reqobj});
            return ((wsResponseObj)(results[0]));
        }
        
        /// <remarks/>
        public void runWSobjAsync(wsRequestObj reqobj) {
            this.runWSobjAsync(reqobj, null);
        }
        
        /// <remarks/>
        public void runWSobjAsync(wsRequestObj reqobj, object userState) {
            if ((this.runWSobjOperationCompleted == null)) {
                this.runWSobjOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrunWSobjOperationCompleted);
            }
            this.InvokeAsync("runWSobj", new object[] {
                        reqobj}, this.runWSobjOperationCompleted, userState);
        }
        
        private void OnrunWSobjOperationCompleted(object arg) {
            if ((this.runWSobjCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.runWSobjCompleted(this, new runWSobjCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org//ws/getScoresXml", RequestNamespace="http://tempuri.org//ws", ResponseNamespace="http://tempuri.org//ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode getScoresXml(
                    string securecode, 
                    string projectid, 
                    string clientid, 
                    string jobid, 
                    string candidateid, 
                    string instrumentid, 
                    string normsetid, 
                    string scale, 
                    string mappingid, 
                    string iscustommapping, 
                    string limitprofile, 
                    string rulebaseid, 
                    string languageid, 
                    string lastname, 
                    string firstname, 
                    string genderid, 
                    string encodedscore) {
            object[] results = this.Invoke("getScoresXml", new object[] {
                        securecode,
                        projectid,
                        clientid,
                        jobid,
                        candidateid,
                        instrumentid,
                        normsetid,
                        scale,
                        mappingid,
                        iscustommapping,
                        limitprofile,
                        rulebaseid,
                        languageid,
                        lastname,
                        firstname,
                        genderid,
                        encodedscore});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void getScoresXmlAsync(
                    string securecode, 
                    string projectid, 
                    string clientid, 
                    string jobid, 
                    string candidateid, 
                    string instrumentid, 
                    string normsetid, 
                    string scale, 
                    string mappingid, 
                    string iscustommapping, 
                    string limitprofile, 
                    string rulebaseid, 
                    string languageid, 
                    string lastname, 
                    string firstname, 
                    string genderid, 
                    string encodedscore) {
            this.getScoresXmlAsync(securecode, projectid, clientid, jobid, candidateid, instrumentid, normsetid, scale, mappingid, iscustommapping, limitprofile, rulebaseid, languageid, lastname, firstname, genderid, encodedscore, null);
        }
        
        /// <remarks/>
        public void getScoresXmlAsync(
                    string securecode, 
                    string projectid, 
                    string clientid, 
                    string jobid, 
                    string candidateid, 
                    string instrumentid, 
                    string normsetid, 
                    string scale, 
                    string mappingid, 
                    string iscustommapping, 
                    string limitprofile, 
                    string rulebaseid, 
                    string languageid, 
                    string lastname, 
                    string firstname, 
                    string genderid, 
                    string encodedscore, 
                    object userState) {
            if ((this.getScoresXmlOperationCompleted == null)) {
                this.getScoresXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetScoresXmlOperationCompleted);
            }
            this.InvokeAsync("getScoresXml", new object[] {
                        securecode,
                        projectid,
                        clientid,
                        jobid,
                        candidateid,
                        instrumentid,
                        normsetid,
                        scale,
                        mappingid,
                        iscustommapping,
                        limitprofile,
                        rulebaseid,
                        languageid,
                        lastname,
                        firstname,
                        genderid,
                        encodedscore}, this.getScoresXmlOperationCompleted, userState);
        }
        
        private void OngetScoresXmlOperationCompleted(object arg) {
            if ((this.getScoresXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getScoresXmlCompleted(this, new getScoresXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org//ws/getScoresObj", RequestNamespace="http://tempuri.org//ws", ResponseNamespace="http://tempuri.org//ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public wsScoreRespObj getScoresObj(wsScoreReqObj reqobj) {
            object[] results = this.Invoke("getScoresObj", new object[] {
                        reqobj});
            return ((wsScoreRespObj)(results[0]));
        }
        
        /// <remarks/>
        public void getScoresObjAsync(wsScoreReqObj reqobj) {
            this.getScoresObjAsync(reqobj, null);
        }
        
        /// <remarks/>
        public void getScoresObjAsync(wsScoreReqObj reqobj, object userState) {
            if ((this.getScoresObjOperationCompleted == null)) {
                this.getScoresObjOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetScoresObjOperationCompleted);
            }
            this.InvokeAsync("getScoresObj", new object[] {
                        reqobj}, this.getScoresObjOperationCompleted, userState);
        }
        
        private void OngetScoresObjOperationCompleted(object arg) {
            if ((this.getScoresObjCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getScoresObjCompleted(this, new getScoresObjCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org//ws/combineScoresXml", RequestNamespace="http://tempuri.org//ws", ResponseNamespace="http://tempuri.org//ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode combineScoresXml(string securecode, string clientid, string scores, string scale) {
            object[] results = this.Invoke("combineScoresXml", new object[] {
                        securecode,
                        clientid,
                        scores,
                        scale});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void combineScoresXmlAsync(string securecode, string clientid, string scores, string scale) {
            this.combineScoresXmlAsync(securecode, clientid, scores, scale, null);
        }
        
        /// <remarks/>
        public void combineScoresXmlAsync(string securecode, string clientid, string scores, string scale, object userState) {
            if ((this.combineScoresXmlOperationCompleted == null)) {
                this.combineScoresXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OncombineScoresXmlOperationCompleted);
            }
            this.InvokeAsync("combineScoresXml", new object[] {
                        securecode,
                        clientid,
                        scores,
                        scale}, this.combineScoresXmlOperationCompleted, userState);
        }
        
        private void OncombineScoresXmlOperationCompleted(object arg) {
            if ((this.combineScoresXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.combineScoresXmlCompleted(this, new combineScoresXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org//ws/combineScoresObj", RequestNamespace="http://tempuri.org//ws", ResponseNamespace="http://tempuri.org//ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public wsScoreRespObj combineScoresObj(wsScoreUtilReqObj reqobj) {
            object[] results = this.Invoke("combineScoresObj", new object[] {
                        reqobj});
            return ((wsScoreRespObj)(results[0]));
        }
        
        /// <remarks/>
        public void combineScoresObjAsync(wsScoreUtilReqObj reqobj) {
            this.combineScoresObjAsync(reqobj, null);
        }
        
        /// <remarks/>
        public void combineScoresObjAsync(wsScoreUtilReqObj reqobj, object userState) {
            if ((this.combineScoresObjOperationCompleted == null)) {
                this.combineScoresObjOperationCompleted = new System.Threading.SendOrPostCallback(this.OncombineScoresObjOperationCompleted);
            }
            this.InvokeAsync("combineScoresObj", new object[] {
                        reqobj}, this.combineScoresObjOperationCompleted, userState);
        }
        
        private void OncombineScoresObjOperationCompleted(object arg) {
            if ((this.combineScoresObjCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.combineScoresObjCompleted(this, new combineScoresObjCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org//ws")]
    public partial class wsRequestObj {
        
        private string emailAddressField;
        
        private string resultPostHeadersField;
        
        private string resultPostBodyTemplateField;
        
        private string resultPostUrlField;
        
        private string notifyListField;
        
        private string returnUrlField;
        
        private string iPAddressField;
        
        private string genderIdField;
        
        private string lastNameField;
        
        private string firstNameField;
        
        private string normsetIdField;
        
        private string reportIdField;
        
        private string clientIdField;
        
        private string jobIdField;
        
        private string projectIdField;
        
        private string instrumentIdField;
        
        private string candidateIdField;
        
        private string secureCodeField;
        
        private string requestTypeField;
        
        private int languageIdField;
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ResultPostHeaders {
            get {
                return this.resultPostHeadersField;
            }
            set {
                this.resultPostHeadersField = value;
            }
        }
        
        /// <remarks/>
        public string ResultPostBodyTemplate {
            get {
                return this.resultPostBodyTemplateField;
            }
            set {
                this.resultPostBodyTemplateField = value;
            }
        }
        
        /// <remarks/>
        public string ResultPostUrl {
            get {
                return this.resultPostUrlField;
            }
            set {
                this.resultPostUrlField = value;
            }
        }
        
        /// <remarks/>
        public string NotifyList {
            get {
                return this.notifyListField;
            }
            set {
                this.notifyListField = value;
            }
        }
        
        /// <remarks/>
        public string ReturnUrl {
            get {
                return this.returnUrlField;
            }
            set {
                this.returnUrlField = value;
            }
        }
        
        /// <remarks/>
        public string IPAddress {
            get {
                return this.iPAddressField;
            }
            set {
                this.iPAddressField = value;
            }
        }
        
        /// <remarks/>
        public string GenderId {
            get {
                return this.genderIdField;
            }
            set {
                this.genderIdField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string NormsetId {
            get {
                return this.normsetIdField;
            }
            set {
                this.normsetIdField = value;
            }
        }
        
        /// <remarks/>
        public string ReportId {
            get {
                return this.reportIdField;
            }
            set {
                this.reportIdField = value;
            }
        }
        
        /// <remarks/>
        public string ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        public string JobId {
            get {
                return this.jobIdField;
            }
            set {
                this.jobIdField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectId {
            get {
                return this.projectIdField;
            }
            set {
                this.projectIdField = value;
            }
        }
        
        /// <remarks/>
        public string InstrumentId {
            get {
                return this.instrumentIdField;
            }
            set {
                this.instrumentIdField = value;
            }
        }
        
        /// <remarks/>
        public string CandidateId {
            get {
                return this.candidateIdField;
            }
            set {
                this.candidateIdField = value;
            }
        }
        
        /// <remarks/>
        public string SecureCode {
            get {
                return this.secureCodeField;
            }
            set {
                this.secureCodeField = value;
            }
        }
        
        /// <remarks/>
        public string RequestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
            }
        }
        
        /// <remarks/>
        public int LanguageId {
            get {
                return this.languageIdField;
            }
            set {
                this.languageIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org//ws")]
    public partial class wsScoreUtilReqObj {
        
        private string clientIdField;
        
        private string secureCodeField;
        
        private string scoresField;
        
        private string scaleField;
        
        /// <remarks/>
        public string ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        public string SecureCode {
            get {
                return this.secureCodeField;
            }
            set {
                this.secureCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Scores {
            get {
                return this.scoresField;
            }
            set {
                this.scoresField = value;
            }
        }
        
        /// <remarks/>
        public string Scale {
            get {
                return this.scaleField;
            }
            set {
                this.scaleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org//ws")]
    public partial class wsScoreRespObj {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private string scoresField;
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string Scores {
            get {
                return this.scoresField;
            }
            set {
                this.scoresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org//ws")]
    public partial class wsScoreReqObj {
        
        private string lastnameField;
        
        private string firstnameField;
        
        private string genderIDField;
        
        private string rulebaseIDField;
        
        private string limitProfileField;
        
        private string isCustomMappingField;
        
        private string mappingIDField;
        
        private string languageIDField;
        
        private string scaleField;
        
        private string normsetIdField;
        
        private string clientIdField;
        
        private string projectIdField;
        
        private string jobIdField;
        
        private string instrumentIdField;
        
        private string candidateIdField;
        
        private string secureCodeField;
        
        private string encodedScoreField;
        
        /// <remarks/>
        public string Lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
            }
        }
        
        /// <remarks/>
        public string Firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
            }
        }
        
        /// <remarks/>
        public string GenderID {
            get {
                return this.genderIDField;
            }
            set {
                this.genderIDField = value;
            }
        }
        
        /// <remarks/>
        public string RulebaseID {
            get {
                return this.rulebaseIDField;
            }
            set {
                this.rulebaseIDField = value;
            }
        }
        
        /// <remarks/>
        public string LimitProfile {
            get {
                return this.limitProfileField;
            }
            set {
                this.limitProfileField = value;
            }
        }
        
        /// <remarks/>
        public string isCustomMapping {
            get {
                return this.isCustomMappingField;
            }
            set {
                this.isCustomMappingField = value;
            }
        }
        
        /// <remarks/>
        public string MappingID {
            get {
                return this.mappingIDField;
            }
            set {
                this.mappingIDField = value;
            }
        }
        
        /// <remarks/>
        public string LanguageID {
            get {
                return this.languageIDField;
            }
            set {
                this.languageIDField = value;
            }
        }
        
        /// <remarks/>
        public string Scale {
            get {
                return this.scaleField;
            }
            set {
                this.scaleField = value;
            }
        }
        
        /// <remarks/>
        public string NormsetId {
            get {
                return this.normsetIdField;
            }
            set {
                this.normsetIdField = value;
            }
        }
        
        /// <remarks/>
        public string ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectId {
            get {
                return this.projectIdField;
            }
            set {
                this.projectIdField = value;
            }
        }
        
        /// <remarks/>
        public string JobId {
            get {
                return this.jobIdField;
            }
            set {
                this.jobIdField = value;
            }
        }
        
        /// <remarks/>
        public string InstrumentId {
            get {
                return this.instrumentIdField;
            }
            set {
                this.instrumentIdField = value;
            }
        }
        
        /// <remarks/>
        public string CandidateId {
            get {
                return this.candidateIdField;
            }
            set {
                this.candidateIdField = value;
            }
        }
        
        /// <remarks/>
        public string SecureCode {
            get {
                return this.secureCodeField;
            }
            set {
                this.secureCodeField = value;
            }
        }
        
        /// <remarks/>
        public string EncodedScore {
            get {
                return this.encodedScoreField;
            }
            set {
                this.encodedScoreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org//ws")]
    public partial class wsResponseObj {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private string candidateIDField;
        
        private string keyField;
        
        private string redirectUrlField;
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string CandidateID {
            get {
                return this.candidateIDField;
            }
            set {
                this.candidateIDField = value;
            }
        }
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string RedirectUrl {
            get {
                return this.redirectUrlField;
            }
            set {
                this.redirectUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void runWSxmlCompletedEventHandler(object sender, runWSxmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class runWSxmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal runWSxmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void runWSobjCompletedEventHandler(object sender, runWSobjCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class runWSobjCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal runWSobjCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsResponseObj Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsResponseObj)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getScoresXmlCompletedEventHandler(object sender, getScoresXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getScoresXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getScoresXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getScoresObjCompletedEventHandler(object sender, getScoresObjCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getScoresObjCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getScoresObjCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsScoreRespObj Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsScoreRespObj)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void combineScoresXmlCompletedEventHandler(object sender, combineScoresXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class combineScoresXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal combineScoresXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void combineScoresObjCompletedEventHandler(object sender, combineScoresObjCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class combineScoresObjCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal combineScoresObjCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsScoreRespObj Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsScoreRespObj)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591